### ISSUE TITLE
1주차 : Chapter1_컴퓨터 네트워크(1~28p)

### ISSUE THREAD

**Issue by shim506** [shim506/cs-study#1]
# 학습 내용

-  컴퓨터 네트워크와 TCP/IP
-  네트워크 전체적 맥락 이해하기

**Comment by shim506** [comment]
https://github.com/shim506/TIL/blob/main/NetworkStudy/README.md

**Comment by ese111** [comment]
https://amuru.tistory.com/247

**Comment by rkolx** [comment]
https://velog.io/@rkolx/컴퓨터-네트워크

**Comment by leekm0310** [comment]
[네트워크 스터디 - 1주차 정리](https://velog.io/@becolorful/Network1%EC%A3%BC%EC%B0%A8-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EA%B0%9C%EC%9A%94-TCPIP-%EA%B0%84%EB%8B%A8-%EC%A0%95%EB%A6%AC)

**Comment by Louie-03** [comment]
https://www.notion.so/1-54cf17c0b37c449c89bccb957068f280
