### ISSUE TITLE
3주차 : Chapter3_트랜스포트 계층(59~80p)

### ISSUE THREAD

**Issue by shim506** [shim506/cs-study#3]
# 학습 내용

-  데이터를 분류하는 트랜스포트 계층
-  TCP 의 비밀

**Comment by leekm0310** [comment]
3주차 학습 정리 제출합니다
https://velog.io/@becolorful/Network3주차-트랜스포트-계층

**Comment by rkolx** [comment]
https://velog.io/@rkolx/트랜스포트-계층의-역할

**Comment by Louie-03** [comment]
https://www.notion.so/3-a77395ae75af446fbe74bee61847a338

**Comment by ese111** [comment]
https://amuru.tistory.com/251

죄송합니다 링크올리는 걸깜빡해서 지금 올립니다

**Comment by shim506** [comment]
https://github.com/shim506/TIL/blob/main/NetworkStudy/Ch3.md
