### ISSUE TITLE
5주차 : Chapter5_하드웨어와 네트워크 인터페이스 계층(123~146P)

### ISSUE THREAD

**Issue by shim506** [shim506/cs-study#6]
# 학습 내용

- 네트워크 인터페이스 계층이 담당하는 영역
- 하드웨어와의 관계

**Comment by ese111** [comment]
https://amuru.tistory.com/253

**Comment by shim506** [comment]
https://github.com/shim506/TIL/blob/4500893776b5eb1ab7bd7a4043115176408fc525/NetworkStudy/Ch5.md

**Comment by Louie-03** [comment]
https://www.notion.so/5-d5d1303260704bdfb4be2e6404f32ab3

**Comment by leekm0310** [comment]
https://velog.io/@becolorful/Network5주차-네트워크-인터페이스-계층
