### ISSUE TITLE
6주차 : Chapter6_보안(147~168)

### ISSUE THREAD

**Issue by shim506** [shim506/cs-study#7]
# 학습 내용

- 보안 프로토콜 적용하기
- 보안 기술의 특징 이해하기

**Comment by rkolx** [comment]
https://velog.io/@rkolx/06.-보안

**Comment by ese111** [comment]
https://amuru.tistory.com/255

**Comment by leekm0310** [comment]
https://velog.io/@becolorful/Network6주차보안
