### ISSUE TITLE
운영체제 2주차: 컴퓨터 시스템 구조

### ISSUE THREAD

**Issue by ese111** [shim506/cs-study#9]

**Comment by ese111** [comment]
https://amuru.tistory.com/manage/posts/

**Comment by rkolx** [comment]
https://velog.io/@rkolx/컴퓨터-시스템의-구조

**Comment by shim506** [comment]
https://www.notion.so/d80732b29298425e885f917788e7f3f6

**Comment by Louie-03** [comment]
https://www.notion.so/2-2692bc184506449d9e3e34a4298e121a
